_BASE_: "../COCO_Base-C2_L_R5021k_640b64_4x.yaml"
DATASETS:
  TRAIN: ("coco_2017_train", "addsd_gen_coco_multi_coco-lvis-vg-vgcut_seed0_superlabel")
  TRAIN_REPEAT_FACTOR: (("coco_2017_train", 0.8), ("addsd_gen_coco_multi_coco-lvis-vg-vgcut_seed0_superlabel", 0.2))
DATALOADER:
  SAMPLER_TRAIN: "WeightedCategoryTrainingSampler"
  BATCH_SAMPLING: True
MODEL:
  WEIGHTS: "../pretrained/resnet50_miil_21k.pkl"