_BASE_: "./Base-C2_L_R5021k_640b64_4x.yaml"
SOLVER:
  CHECKPOINT_PERIOD: 20000
  BASE_LR: 0.0001
  MODEL_EMA: 0.999

INPUT:
  INST_POOL: false #true https://github.com/yoctta/XPaste/issues/5
  # INST_POOL_PATH: "/mnt/data/LVIS_instance_pools.json"
  INST_POOL_FORMAT: "RGBA"
  USE_COPY_METHOD: "self_copy"
  USE_INSTABOOST: false
  MASK_FORMAT: bitmask
  CP_METHOD: ['basic']
  RANDOM_ROTATE: false
  INST_POOL_SAMPLE_TYPE: "cas_random"
  TRAIN_SIZE: 640